### PR TITLE
Use alarm list to get counts (SCRD-7696)

### PR DESCRIPTION
**Pull request by eapodaca**

### CODE REVIEW

**Comment by eapodaca** [comment]
Unfortunately this is just a band-aid fix. The alarms count api endpoint causes counts to be incorrect in other places in the opsconsole.

**Comment by ghost** [comment]
@eapodaca  I am just wondering the reason to use count is that data could be huge, pulling all the data back might has some issues. I remember the backend implemented paging to avoid pulling all the data back.

**Comment by ghost** [comment]
@eapodaca  sorry only want to put the comments,  for some reason clicked the wrong button.

**Comment by eapodaca** [comment]
Currently working on upstreaming a backend fix for this to monasca-api.

**Pull request closed without merging**
